project_id = "jplgtzhbdiajlrrwurqq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54329
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
enable_manual_linking = false

[auth.external.apple]
enabled = false
client_id = ""
secret = "env(AUTH_APPLE_SECRET)"

[auth.external.azure]
enabled = false
client_id = ""
secret = "env(AUTH_AZURE_SECRET)"
url = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = "env(AUTH_BITBUCKET_SECRET)"

[auth.external.discord]
enabled = false
client_id = ""
secret = "env(AUTH_DISCORD_SECRET)"

[auth.external.facebook]
enabled = false
client_id = ""
secret = "env(AUTH_FACEBOOK_SECRET)"

[auth.external.figma]
enabled = false
client_id = ""
secret = "env(AUTH_FIGMA_SECRET)"

[auth.external.github]
enabled = false
client_id = ""
secret = "env(AUTH_GITHUB_SECRET)"

[auth.external.gitlab]
enabled = false
client_id = ""
secret = "env(AUTH_GITLAB_SECRET)"

[auth.external.google]
enabled = false
client_id = ""
secret = "env(AUTH_GOOGLE_SECRET)"

[auth.external.keycloak]
enabled = false
client_id = ""
secret = "env(AUTH_KEYCLOAK_SECRET)"
url = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = "env(AUTH_LINKEDIN_SECRET)"

[auth.external.notion]
enabled = false
client_id = ""
secret = "env(AUTH_NOTION_SECRET)"

[auth.external.slack]
enabled = false
client_id = ""
secret = "env(AUTH_SLACK_SECRET)"

[auth.external.spotify]
enabled = false
client_id = ""
secret = "env(AUTH_SPOTIFY_SECRET)"

[auth.external.twitch]
enabled = false
client_id = ""
secret = "env(AUTH_TWITCH_SECRET)"

[auth.external.twitter]
enabled = false
client_id = ""
secret = "env(AUTH_TWITTER_SECRET)"

[auth.external.workos]
enabled = false
client_id = ""
secret = "env(AUTH_WORKOS_SECRET)"

[auth.external.zoom]
enabled = false
client_id = ""
secret = "env(AUTH_ZOOM_SECRET)"

[functions.analyze-resume]
verify_jwt = false